### ISSUE TITLE
mash absent from bioconda recipe

### ISSUE THREAD

**Issue by apredeus** [gtonkinhill/panaroo#50]
Hello, 

I was trying to run panaroo-qc, and it fails because it couldn't find mash. Works fine after installing. So, probably missing mash in bioconda recipe. 

Thanks!

**Comment by tseemann** [comment]
Seems it is missing
```
requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - networkx
    - numba
    - numpy 
    - mkl
    - scipy
    - scikit-learn
    - gffutils
    - biopython
    - joblib
    - tqdm
    - python-edlib
    - matplotlib
    - plotly
    - dendropy
    - cd-hit
    - mafft
```
